//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ChilliSource Cloud Web")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0+1.Branch.master.Sha.fc858aa6b8f48b45adb045b24535552b1558bd8c")]
[assembly: AssemblyCopyright("Copyright Blue Chilli Technology Pty Ltd 2017")]

